### ISSUE TITLE
Fatal error when deleting a Registered App

### ISSUE THREAD

**Issue by lexpostma** [akirk/enable-mastodon-apps#179]
As the title says, I’m getting a fatal error when I delete a Registered App.

> Fatal error: Uncaught Error: Call to undefined function santize_text_field() in /wp-content/plugins/enable-mastodon-apps/templates/admin-header.php:114 

Stack trace (slightly edited to remove server path):
```
#0 /wp-includes/template.php(810): require_once() 
#1 /wp-content/plugins/enable-mastodon-apps/templates/registered-apps.php(11): load_template() 
#2 /wp-includes/template.php(810): require_once('/var/www/lexpos...') 
#3 /wp-content/plugins/enable-mastodon-apps/includes/class-mastodon-admin.php(475): load_template() 
#4 /wp-content/plugins/enable-mastodon-apps/includes/class-mastodon-admin.php(105): Enable_Mastodon_Apps\Mastodon_Admin->admin_registered_apps_page() 
#5 /wp-includes/class-wp-hook.php(324): Enable_Mastodon_Apps\Mastodon_Admin->admin_page() 
#6 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() 
#7 /wp-includes/plugin.php(517): WP_Hook->do_action() 
#8 /var/w in /wp-content/plugins/enable-mastodon-apps/templates/admin-header.php on line 114
```

**Comment by akirk** [comment]
Thank you, I'll fix this in the next version!
